# Generated by Django 2.1.2 on 2018-10-29 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBkpt',
            fields=[
                ('rptcode', models.CharField(max_length=159, primary_key=True, serialize=False)),
                ('tajukrpt', models.TextField()),
                ('penulisrpt', models.EmailField(max_length=254)),
                ('tarikhrpt', models.DateTimeField(default=django.utils.timezone.now)),
                ('share_to_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBorg',
            fields=[
                ('orgname', models.TextField()),
                ('orgcode', models.CharField(default='orgcode98', max_length=159, primary_key=True, serialize=False)),
                ('orgpass', models.CharField(default='orgpass98', max_length=159)),
                ('org_ppw_done', models.IntegerField(default=0)),
                ('org_rpt_done', models.IntegerField(default=0)),
                ('org_subscription_free', models.BooleanField(default=False)),
                ('org_subscription_paid', models.BooleanField(default=False)),
                ('org_subs_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DBppw',
            fields=[
                ('ppwcode', models.CharField(max_length=159, primary_key=True, serialize=False)),
                ('tajukppw', models.TextField()),
                ('penulisppw', models.EmailField(max_length=254)),
                ('tarikhppw', models.DateTimeField(default=django.utils.timezone.now)),
                ('tujuan', models.TextField()),
                ('latar', models.TextField()),
                ('objektif', models.TextField()),
                ('anjuran', models.TextField()),
                ('cadangantarikh', models.TextField()),
                ('penyertaan', models.TextField()),
                ('ajk', models.TextField()),
                ('impkewangan', models.TextField()),
                ('kesimpulan', models.TextField()),
                ('lampiran', models.FileField(upload_to='hafyq/ppwfile')),
                ('reportstatus', models.BooleanField(default=False)),
                ('stats_peserta', models.IntegerField(default=0)),
                ('stats_views', models.IntegerField(default=0)),
                ('stats_budgets', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperworkManagement.DBorg')),
            ],
        ),
        migrations.AddField(
            model_name='dbkpt',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperworkManagement.DBorg'),
        ),
        migrations.AddField(
            model_name='dbkpt',
            name='ppwcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperworkManagement.DBppw'),
        ),
    ]
