# Generated by Django 2.1.2 on 2018-10-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBkpt',
            new_name='DBrpt',
        ),
    ]
