# Generated by Django 2.1.2 on 2018-11-23 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0002_auto_20181029_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='dborg',
            name='stats_jumlah_budgets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dborg',
            name='stats_jumlah_peserta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dborg',
            name='stats_jumlah_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='stats_budgets_hadiah',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='stats_budgets_makan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='stats_budgets_penginapan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='stats_budgets_transport',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='stats_tarikh',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dbppw',
            name='stats_budgets',
            field=models.FloatField(default=0),
        ),
    ]
