# Generated by Django 2.1.2 on 2018-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0003_auto_20181123_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='dborg',
            name='org_desc',
            field=models.TextField(default=' description '),
        ),
    ]
