# Generated by Django 2.1.2 on 2018-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0004_dborg_org_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbppw',
            name='jawatanpenulis',
            field=models.CharField(default='Jawatan', max_length=159),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='jawatansokong',
            field=models.CharField(default='Jawatan', max_length=159),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='lokasisokong',
            field=models.CharField(default='Lokasi', max_length=159),
        ),
        migrations.AddField(
            model_name='dbppw',
            name='namasokong',
            field=models.CharField(default='Nama', max_length=159),
        ),
    ]
