# Generated by Django 2.1.2 on 2018-12-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0006_dbppw_ppwdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dborg',
            name='org_desc',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='org_ppw_done',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='org_rpt_done',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='org_subs_date',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='org_subscription_free',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='org_subscription_paid',
        ),
        migrations.RemoveField(
            model_name='dborg',
            name='stats_jumlah_views',
        ),
    ]
