# Generated by Django 2.1.2 on 2018-12-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperworkManagement', '0008_auto_20181208_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbppw',
            name='lampiran',
        ),
    ]
